""" Shared constant """

BASH_FILE = "launch_job.sh"
MPI_FILE = "mpi_parallel.py"
DS_FILE = "dag.py"
SERIAL_FILE = "data.p"
INPUT_FILE = "input.yml"
OUTPUT_FOLDER = "output"
PBS_PREFIX = "#PBS"
MODULE_PREFIX = "module load"
MPI_PREFIX = "time mpirun"
BASH = "#!/bin/bash"
DATA_DIR = "$PBS_O_WORKDIR" 
WARNING_PREFIX = "[WARNING]"
ERROR_PREFIX = "[ERROR]"